### ISSUE TITLE
Person Agent Clobbering

### ISSUE THREAD

**Issue by chadmart** [usc-csci201-fall2013/simcity201#21]
In the past, each agent has needed to do 1 thing at a time, but now the person is much more complicated. For example, you could be trying to cook at home, but be out of food. So you have to so to the market, but you can have work soon. So in real life you would go to work, then market, then make food, and maybe the bank in between.

In the restaurant design, we would use an enum to control which task to go to. This will not work for the person. We need separate priorities to solve this. The first thing that comes to mind is a boolean for each task and have the scheduler assign priorities for each. But the multiple booleans is usually a red flag that there is a more readable way of doing things. So then maybe some sort of priority data structure would have to be used?

@dwilczyn @crowley1958 @alghanmi

**Comment by choiRyan** [comment]
Is PriorityQueue inadequate or something? (Or PriorityBlockingQueue?)

**Comment by dwilczyn** [comment]
Why did you title this PersonAgent Clobbering. What's being clobbered?

**Comment by chadmart** [comment]
The enum to control which task to go to.

**Comment by dwilczyn** [comment]
chadmart is suggesting some scripting/planning ideas. That is a very practical way of doing things in real life, but might be too complicated for us on this project. For example, look at this rule:

if justWokeUp and itIsAWorkday then doWorkdayScript(); 
//an action that eats, goes to Work, shops afterward if necessary, goes to bank if necessary, goes home.

Hmm, not so easy, how do get out of a script if an emergency happens. Remember, we don’t want actions to take too long, so we can get back to our scheduler. Scripting is very much like using a finite state machine. It had better be simple. That's why chadmart is rightly nervous.

I doubt I would do this now or use a PriorityQueue. I wouldn't make person agent a finite state machine either. His incarnation as a CustomerRole will be. I would try having rules in the right order first. The rules might be more complicated, but it's only one agent. Let's look at your case about eating, shopping, working. In the following all my predicates are stub functions:

if NeedToBeAtWorkSoon() {
    if NotStarving() then gotoWork(); //this will put you in restaurantCustomerRole
    else if thereIsFoodAtHome() then EatAtHome(); //assumes that you don't take too long
    else ?? //you have to make some decisions here: fastFoodRestaurant? Call Boss?
}
if hungry() {
    if haven'tEatenOutInAWhile() and haveLotsOfMoney() then eatOut();
    else if thereIsFoodAtHome() then EatAtHome();
    else gotoMarket(); //this will put you in marketCustomerRole
}
if needToHaveABankInteraction() then gotoBank(); //this will put you in the BankCustomerRole

Or something like that...

Now, of course, you need to design those stubs. You can do it. Also, during early stages of design/implementation, you might not get perfect behavior that chadmart was aspiring to. We can talk later about alternatives like using scripts, decision trees, Karnaugh maps, etc.

I'm glad chadmart brings these issues up. It shows how sophisticated even our simple decisions are.
