### ISSUE TITLE
Phone Numbers in Restaurant - Agent, Method Forwarding, or Shared Data

### ISSUE THREAD

**Issue by brandonsbarber** [usc-csci201-fall2013/simcity201#28]
@dwilczyn 
Just wanted to continue our discussion from class today.

Basically, my group has been thinking about several different possible solutions of buildings talking to one another (via their agents) and whether they should be agents in themselves.

Shared data does not appeal, because if the host or cook or anyone else changes, then we cannot truly get our messages sent. This begs that we have a way of determining who the current host is or current cashier or anything else.

It truly comes down to whether a Restaurant or anything else should handle messages and actions (which is a little counter-intuitive from an "agent") or pass along events. In this line of thought, a Restaurant would receive an order from the market and order its cooks to resolve it.

Otherwise, a restaurant would strictly pass along a message of the order being delivered to the cook (if we think about it, food is delivered to the Restaurant but the cook is the one who does stuff with it).

I'm having some trouble articulating this difference, but in some cases it makes sense to forward messages and other times it makes sense to actually perform actions. It does not seem like a restaurant would need its own thread to run, but I would like your input on this.

**Comment by dwilczyn** [comment]
I HATE the idea of a RestuarantAgent. Let's try to reason through this phone number thing. I think it's much easier than we have made it. First how does a particular run of SimCity201 get started? Something like this:
1) The SimCity201 panel creates PersonAgents and keeps them in a list. [Imagine a script that says create 100 PersonAgents, naming them P1, P2, ...P100.] 
2) Then the SimCity201 panel creates a RestaurantPanel for each restaurant in your system and calls it for initialization. 
3) Each RestauantPanel create an instance of the HostRole, CookRole, and CashierRole. I assume you still have the mechanism to create WaiterRoles the same way, from the GUI.
4) Now you need a mechanism to assign each of those roles to one of P1, P2, ... and you tell every person about the host association so that the PersonAgents can populate their contact list.
5) Now everything is linked up and the SimCity201 simulation can run. [I'm ignoring animation issues here.] A PersonAgent gets hungry and goes to a Restaurant, like I designed in class Monday and Tuesday of this week.

Restaurant {
Location location;
Host host;
string customerRole; //value is something like “Restaurant1CustomerRole”
Menu m;
String type;}

GoToRestaurant(){
Restaurant r = restaurants.ChooseOne() ; //restaurants comes from the contact list
TransportationMethod tm = PickOne(r); //Someone has to do this.
DoGoTo(r.location, tm); //It’s probably more complicated than this.
Role c = CustomerFactory(r.customerRole); 
roles.add(c);
c.active = T;
r.host.ImHungry((Customer) c); 
}
Something like that. Now the big issue is what happens if the Host of this restaurant is fired and a new Host is assigned? The idea raised in the post is that maybe we need some kind of phone system so that a person calls the phone number and whoever is currently the Host answers it. Then the question of a RestaurantAgent or shared data or what is needed to make that happen. 

I claim nothing is needed! Let’s investigate how a Host change happens in a restaurant. A PersonAgent, say P1, was assigned an instance, say H1, of the Restaurant1HostRole. Say P1 is fired as the Host of Restaurant1. That means:
1)  P1 removes the role from his list. So his scheduler  will no longer  call the HostRole scheduler. For the moment H1 is “disabled” but is still able to receive messages.
2)  Say P2 is hired to replace P1.  P2 adds H1 to its roles. Now H1 is reenabled, since P2’s scheduler  will call H1’s scheduler.
3)  And that’s it! Nothing else changes. The key point is that the ROLE didn’t change, only the assignment to the PersonAgent changed.

So, the H1 entry in every PersonAgent contact list is CONSTANT. It never changes once SimCity201 is running. So, no need for phone numbers. The host role in the contact list is the analog to a phone number. Now, of course, a  Restaurant could explode, but let’s worry about that in v3.

And, another one of my requirements is that this is realistic. If a host is fired in the middle of the day, the new host must  be given all the CURRENT host data of the restaurant so that he can seamlessly take over. Well, all that data IS IN the host role. Perfect!
