### ISSUE TITLE
Animation moving really slowly

### ISSUE THREAD

**Issue by wmcnicho** [usc-csci201-fall2013/simcity201#58]
After implementing all of the individual animation components of each building and combining them into one program we are reaching problems where our animation is moving extremely slowly.  Has anyone else run into a similar problem? Should there be a thread responsible for the animation of each building?

**Comment by KeithDeRuiter** [comment]
There should probably not be a thread for each building animation, since all of the GUI and component painting will be handled by the Java Swing thread.  Could you elaborate a bit more on your problem or some symptoms of it?  I saw your post in Issue #59, are you sure that (a) your updates aren't ever being called from a paintComponent method, and that (b) you don't try and force things to draw that aren't a visible component?  In the original restaurant, each AnimationPanel had its own Timer that ran a task calling repaint() to repaint the GUI.  If you are manually doing that now, but all of the panels are still telling themselves to update, the performance might drop.  Hard to say what your problem specifically might be though...

**Comment by wmcnicho** [comment]
Well I'm not entirely sure if it's an animation specific issue or perhaps an issue of an overloaded heap.  The way that I have implemented the gui is that each individual "AnimationPanel" is responsible for animating the elements inside it but the paint method will only be called on the currently displayed screen.  The updateLoaction is called on all of the AnimationPanels by a data structure that we  created that contains all of the AnimationPanels.

In reference to your points

(a) Our updates are being called in the paintComponent method for the CityPanel which calls the paint methods for the current display screen after updating positions in every screen.

(b) Yes, only visible things are being repainted.

The code in this implementation works but it is extremely slow and sometimes freezes.

**Comment by wmcnicho** [comment]
For one reason or another I've tried running all of our buildings at the same time again and everything is animating perfectly. I guess my computer was just having a bad day when I made this post yesterday.

**Comment by ChaseWagoner** [comment]
@wmcnicho I'm having this problem as of today also. Is there anything you can remember doing between the slow animations and running perfectly? Currently about 1/30 runs it's about 30% speed, and the rest are about 10% speed.

**Comment by wmcnicho** [comment]
@cwagoner We simply commented out all of the different buildings except the one we were testing. After a day or so of coding and a computer reset everything is now working fine. Best of luck
