### ISSUE TITLE
Unit Testing Event Log

### ISSUE THREAD

**Issue by liangvic** [usc-csci201-fall2013/simcity201#66]
I'm a little confused about having an EventLog in the Agent/Role classes. 
Half my team was docked points, and the other half wasn't for having it in there.
Clarification please?

**Comment by dwilczyn** [comment]
Is this about restaurant v2.2?

**Comment by alghanmi** [comment]
@liangvic &ndash; if this is a v2.2 grading issue, please follow the proper procedure by responding to your grader via the issue tracker and @ mentioning myself if you were unable to reach a satisfying conclusion with them.

If this is not a grading dispute, then please clarify your question.

**Comment by liangvic** [comment]
This is with regards to simcity v1. Sorry for the confusion!

**Comment by pbradshawusc** [comment]
The question is whether event logs should be in the actual agents for the simcity project. We know that they should be in the mock agents/roles for testing, but some people were told in the previous restaurant v2.2 to put them in the actual agents as well as the mock agents. However, members of our team were marked off points for putting event logs in actual agents; we just want to clarify whether they should be there or not.

**Comment by dwilczyn** [comment]
Event logs were originally designed for unit testing as a necessary alternative to print statements. Since event logs were used by both mocks and real agents/roles during unit testing, they should be part of EVERY agent/role, shouldn't they? All your SimCity201 code should be unit tested. Agent code should not be different just because it is put in a unit test environment--how could that be maintained.

What points were taken off? From a lab score? From what?

**Comment by pbradshawusc** [comment]
The points were taken off from v2.2, but the issue was resolved a while ago. Thank you for the clarification. We will add event logs to every role and agent for testing purposes.
