### ISSUE TITLE
Different Lagging

### ISSUE THREAD

**Issue by lizhifan** [usc-csci201-fall2013/simcity201#69]
When I run my simcity project I experience quite a lot of lag. However, all of my teammates when running the same project do not experience this lag. I was wondering if there was anything I could do so that I wouldn't experience this lag.

**Comment by eerie444** [comment]
buy a faster computer

**Comment by diegovb** [comment]
www.amazon.com/BlackFriday

**Comment by lizhifan** [comment]
thnx.

**Comment by diegovb** [comment]
c:

**Comment by smoran02** [comment]
I have the same issue and would appreciate a serious response. I don't really think this is the appropriate place for sarcastic remarks or juvenile attempts at humor.

My computer is completely fine (retina 13" 8gigs of ram). I have tried increasing the heap space for Eclipse but that didn't solve the issue. Does anyone know how to reduce the lag so I can watch the simulation at faster than crawling speed?

**Comment by ztanner** [comment]
You need to use a Java profiler and figure out what is eating the most resources.

**Comment by ukby1234** [comment]
did u try the jdk 1.7 instead of the jdk provided by apple?

**Comment by johngtimms** [comment]
@ztanner Could you post a link to a StackOverflow with instructions on how to do what you're describing?

This doesn't address the issue of the animation working for some people and not for others (assuming that the code is identical) but when my animation lags, it's usually due to a runaway scheduler that is looping constantly and isn't returning `false` when it should.

**Comment by alghanmi** [comment]
When I needed a lightweight profilers for an application I was testing, I found [VisualVM](https://visualvm.java.net/profiler.html) to be quite helpful. It does two important profiling tasks:
- CPU profiling - to check for infinite loops, time-consuming components
- Memory profiling - you have first experience with this.

> http://visualvm.java.net/download.html

Documentation is pretty good too and it has an [eclipse plugin](http://visualvm.java.net/eclipse-launcher.html).

**Comment by lshiffer** [comment]
If it's a laptop, is it plugged in?  I had a thinkpad that lagged when not plugged in as it would reduce processing to save battery.

**Comment by smoran02** [comment]
@ukby1234 Thank you. Using JDK 1.7 instead of the Mac provided one fixed my issue.

**Comment by Rancho06** [comment]
Hello guys. I know this issue is closed. But I just wanna further ask about upgrading from JDK1.6 to JDK1.7. My eclipse is now lagging. But after I tried upgrading to JDK1.7, the program cannot even be run any more. And it showed errors like below:

![screen shot 2013-12-04 at 4 02 30 pm](https://f.cloud.github.com/assets/3290024/1678837/95fe2be0-5d40-11e3-83cb-85a47c13fd7f.png)

Anyone has idea what's going on? Thanks!

**Comment by tginick** [comment]
Have you tried recompiling your code? You may have to clean your project by going to Project -> Clean

I also noticed you're using Mac OSX. Notice the java path at the top of this screen shot
"/System/Library/Java/JavaVirtualMachines/1.6.0.jdk........." Not sure if the default java in Mac OS X supports java 1.7

This issue might help you more
http://stackoverflow.com/questions/7669899/how-to-run-eclipse-indigo-on-jdk-1-7-osx

**Comment by Rancho06** [comment]
I just tried Project -> clean, still not working though.
I do know at least 2 of my friends having the same problem. For example in my group of 5 people, 3 people use JDK1.7 and me and another guy use JDK1.6. My workspace is apparently not compatible with other people's code like "switch(String)".

**Comment by ztanner** [comment]
You probably have the wrong compiler version set?
http://stackoverflow.com/questions/2906026/java-lang-unsupportedclassversionerror-in-eclipse

**Comment by tginick** [comment]
I have a feeling this has to do with the default Java included with Mac OS X. I've had this problem before, decided it was too much trouble, and just did everything on Windows. So far everything's been fine, even on 1.7, probably because I could just install the newest JDK.

The root of the problem is probably because the class files were compiled using compliance level 1.7 but your java runtime only supports 1.6. I can't see what the rest of the error says but it probably has a 51 in there...right?

These are the java class versions. 51 corresponds to java 1.7

```
J2SE 8 = 52,
J2SE 7 = 51,
J2SE 6.0 = 50,
J2SE 5.0 = 49,
JDK 1.4 = 48,
JDK 1.3 = 47,
JDK 1.2 = 46,
JDK 1.1 = 45
```

If this really is the case, there are probably ways to install java 1.7 on your mac... 
If it's not too much trouble, you could also switch back to 1.6 haha

**Comment by Rancho06** [comment]
Thanks for the valuable advice @ztanner @tginick . 

I got it fixed, but it's not because of JRE version or compiler version or someting The problem is due to that we should explicitly configure the 1.7 JRE library as could be used by the system after setting it as the default environment. So the system has 1.7 JRE set up, but didn't know it could or should be used. I thought eclipse would do that automatically since it's set to be the default environment, but somehow it was not... So just manually configure JRE1.7 and everything looks fine now.
