### ISSUE TITLE
Java updating multiple variables

### ISSUE THREAD

**Issue by johngtimms** [usc-csci201-fall2013/simcity201#76]
I had the following code in a constructor:

```
this.dateOne = someDate;
this.dateTwo = someDate;
```

I found out that whenever I changed `dateOne`, `dateTwo` also got changed even though I didn't want it to.

I think I (more or less) understand _why_ this was happening, but what I want to know is if this is the correct solution:

```
this.dateOne = new Date(someDate.getTime());
this.dateTwo = new Date(someDate.getTime());
```

Actually, I'm surprised I haven't run into this issue earlier.

@alghanmi @ukby1234

**Comment by alghanmi** [comment]
The Java Tutorial has a short and sweet code example that will help you understand the object life-cycle:

> http://docs.oracle.com/javase/tutorial/java/javaOO/objects.html

**Comment by diegovb** [comment]
This is because dates are objects, so after 

```
this.dateOne = someDate;
this.dateTwo = someDate;
```

`dateOne` and `dateTwo` would point to the same object.

**Comment by alghanmi** [comment]
@johngtimms, to answer your question we need to check the return type of [`someDate.getTime()`](http://docs.oracle.com/javase/7/docs/api/java/util/Date.html#getTime%28%29) which turns out to be a `long int`. 

Primitives in java are not objects. Also, you are creating brand new `Date` objects, so you are OK.

**Comment by johngtimms** [comment]
Thanks @alghanmi. That's what I was wanting to know.
