### ISSUE TITLE
resetting to different days of the week and Java GC

### ISSUE THREAD

**Issue by chadmart** [usc-csci201-fall2013/simcity201#80]
I am trying to design a reset button that will reset to a different day of the week, but I am not sure if I will create a memory leak. Does anyone know how Java garbage collection works, and how I can prevent a memory leak when resetting my simulation?

@alghanmi @dwilczyn @crowley1958

**Comment by pixelprizm** [comment]
Since the garbage collector will deallocate all memory that doesn't have any remaining references to it, the only way to get a memory leak would be to continuously add new objects to a list, as in:

``` java
while(true) { myCustomers.add(new MyCustomer(...)); }
```

(the reference to each item doesn't go away unless you remove that item from the list).  As long as you're not doing that, you should be fine.

Does that help? Also, someone correct me if I'm wrong.

**Comment by chadmart** [comment]
Well, I still don't understand what it means to not have any remaining references. If the any thread cannot reference it or just the main 1? If I am deleting a personAgent, do I have to stop the the thread and make sure no threads have references to it? Do I have to worry about roles or other non-threaded objects that might reference it, even if they are not referenced by any other threads?

**Comment by pixelprizm** [comment]
Yeah, threads don't matter for garbage collection.  The memory won't be deallocated until every single reference to the object in question is deleted.  So you would have to make sure that each pointer (thread or not) to the PersonAgent instance that you want to delete will either be set to point to another PersonAgent or set to null.  Threads don't matter, just the variables (pointers/references) that hold the address of / point to the PersonAgent.

**Comment by tginick** [comment]
Here's a simple example. Suppose you had this code snippet.

``` java
List<String> someList = new ArrayList<String>();
```

This creates an ArrayList. You can reference it through the variable someList.
Now if instead you have this snippet...

``` java
List<String> someList = new ArrayList<String>();
someList = Collections.synchronizedList(new ArrayList<String>());
```

someList is now referencing the synchronized list that you get from calling Collections.synchronizedList. What happened to the first one you initialized? It's gone now since there aren't any more references to it. Basically if there's no way to access a piece of data anymore, it can be scheduled for garbage collection.

**Comment by alghanmi** [comment]
Keep in mind that the Java Garbage Collector uses a non-deterministic algorithm to decide when to run. You can use the following function to "suggest" to the garbage collector to run, but you can't say - using the standard JDK - run now:

``` java
 System.gc()
```

The documentation for the above method is here:

> http://docs.oracle.com/javase/7/docs/api/java/lang/System.html#gc()

As @egauderman said, the object needs to be in memory with no references pointing to it. Unlike C/C++ you can't deallocate memory from the heap.

See this video:

> https://www.youtube.com/watch?v=5jubCfyuqvA

**Comment by chadmart** [comment]
Thank you that video was very helpful.

If object O_1 has no references pointing to it and O_1 points to other objects, O_2 and O_3, that have no other references except O_1. Are O_1, O_2, and O_3 eligible for garbage collection?

**Comment by diegovb** [comment]
Yes

**Comment by diegovb** [comment]
Maybe it takes more than one collection "cycle", but eventually they'll all be gone.

**Comment by pixelprizm** [comment]
Yeah, you have no way of knowing for sure exactly when the garbage collector will run, but you know that a memory overflow won't happen due to the garbage collector not deallocating soon enough; i.e., the garbage collector will definitely run sometime before you max out on memory.

**Comment by chadmart** [comment]
Thanks for all the help.

If I am understanding this right, the only way to cause a memory leak is if there are 2 objects that reference each other and nothing references them. So you cannot use them, but they are not eligible for garbage collection.

Am I right? or is java smart enough to detect these cases?

**Comment by pixelprizm** [comment]
If I had to guess, I would say that Java is probably smart enough. I think in that case it actually would involve threads; i.e. if there are no more references to either of the 2 objects AND there are no threads currently running in either of them, they'll be deleted since there is no way for them to ever be used.  I guess a good way to think about it is "is it possible for the code in these objects to ever be run? If no, they will be deleted. If yes, they won't be deleted.

**Comment by chadmart** [comment]
@alghanmi or someone else can you confirm egauderman comment?

**Comment by dwilczyn** [comment]
As I understand it, Java memory leaks are not the same as C/C++ memory leaks where memory is allocated and not deallocated correctly by the programmer. Java can "hold" onto memory that you THINK has no references in strange ways, often with gui code and static declarations. I'm certainly not expert with these instances. I just googled "java memory leaks" and got many hits. I read this one:
http://www.ibm.com/developerworks/library/j-leaks/
Maybe it will help.
