### ISSUE TITLE
Tracer slows down animation significantly

### ISSUE THREAD

**Issue by colortheskyjade** [usc-csci201-fall2013/simcity201#86]
When trying to implement the tracer code provided by a cp (in simcity/gui/trace of this repo), our team has found that just starting the tracer and not printing to it will significantly slow down all our animations. Has anyone been able to add their stack trace without this happening? 

@KeithDeRuiter

**Comment by KeithDeRuiter** [comment]
Hmm, what do you mean by starting it and not printing?  Do you mean the trace panel itself (the actual display), or just the alert log?  At what point does the animation start to slow down? (right away, after a long time, after you change something)

**Comment by colortheskyjade** [comment]
Just opening the instance of the tracer in a window will slow any animation down, even if we never call a Do() function to print to the log. We changed the scheduleAtFixedRate function so that it repaints less often, but is there a better way to do this?

**Comment by Valakor** [comment]
I have a similar problem, though it isn't because of the Trace Panel. For me, I have a panel that displays a currently selected PersonAgent's information. Whenever I click on a new PersonAgent in the list of PersonAgents, there's a slight slow down in animation in our City view. I've come to believe that this is because the application is shifting focus to the new window, causing other windows to either repaint less or not repaint during this focus shift, making it look like animation is slowing down.
This is only speculation right now though.

**Comment by KeithDeRuiter** [comment]
Hmm.. I don't know for sure about the tracepanel slowdown, but one problem that would lead to animation speed inconsistencies is having your updates and movement be dependent on frame rate.  That's how the restaurant worked, but if you are having issues with that, then you could make framerate independent update logic.  Instead of only updating everything's position when the component is painted, you could pass a delta time (or calculate it inside) to your update function.  Then, give everything a speed/velocity (like 12 pixels per second or something) and use basic distance = rate \* time math to figure out how far it moved and where it should be.  Then, even if the painting of your component slows down, the math will still work out to keep everything going at the speed you expect it to.  You could try something like that is this ends up being a big concern for you.

colortheskyjade, are you trying to manually paint the trace panel or something?  Or is the scheduleAtFixedRate method you refer to the one that schedules all of your other animation drawing/updating?

**Comment by johnsonh** [comment]
Hey Keith, I'm on colortheskyjade's team. I think scheduleAtFixedRate is a method of the timer, and it repaints just the panel every X milliseconds. I think we figured it out though; increasing X made everything run reasonably.
